services:
  - type: web
    name: envision2k26
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --worker-class eventlet -w 1 run:app"
    rootDirectory: flask_app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_ENV
        value: production
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: firebase-service-account.json
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
