services:
  - type: web
    name: envision2k26
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --worker-class gevent -w 1 run:app"
    rootDirectory: flask_app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_ENV
        value: production
      - key: EMAIL_SENDER
        value: cireportingsystem@gmail.com
      - key: EMAIL_SMTP_HOST
        value: smtp.gmail.com
      - key: EMAIL_SMTP_PORT
        value: 587
      - key: EMAIL_SMTP_USERNAME
        value: cireportingsystem@gmail.com
      - key: EMAIL_SMTP_PASSWORD
        sync: false
      - key: EMAIL_SMTP_USE_TLS
        value: true
      - key: EMAIL_SMTP_TIMEOUT
        value: 10
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: cirs-uploads